application: curious-eyes-third
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# static assets
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /styles
  static_dir: static/styles

- url: /scripts
  static_dir: static/scripts

- url: /images
  static_dir: static/images

# application
- url: .*
  script: main.app
  login: admin

# Endpoints handler

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
